version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "hello world 1"
      - run : echo "hiiii"
      - run : sleep 20 
  test1:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "test 1"

  test2:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "test2"  
      
workflows:
  version: 2
  default:
    jobs:
      - build
      - test1
      - test2
      
      
      #test
